# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68d064190b9a60664b6c644cfac7bc49"
name = "first-avada-app"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,read_script_tags,write_script_tags,read_themes,write_themes,read_metaobject_definitions, write_metaobject_definitions,read_metaobjects,write_metaobjects"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
