# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebd2b68ab19c1438fc7662c19b57699c"
name = "sale-pops-app"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,read_script_tags,write_script_tags,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
